# Use functional image already on ghcr
FROM ghcr.io/the-rhizodynamics-robot/file-sorting-env@sha256:b304899a4368f116117f4233840c226e0fc239983b219b8f135981090e9b6767
# Download model files from Hugging Face
RUN mkdir -p /app/models 
RUN wget -O /app/models/SeedInference.h5 https://huggingface.co/iwtwb8/root_robot_models/resolve/main/SeedInference.h5 && \
    wget -O /app/models/qrInference.h5 https://huggingface.co/iwtwb8/root_robot_models/resolve/main/qrInference.h5
